#!/usr/bin/env python3
"""
Create test issues for GitHub repository automation testing

This script creates realistic test issues in the configured repository
to verify GitHub API integration and permissions.
"""

import sys
import os
from datetime import datetime

# Add the core directory to Python path so we can import github_client
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'core'))

from github_client import GitHubClient

def create_automation_test_issue():
    """
    Create a test issue demonstrating DevOps Agent GitHub integration
    """
    try:
        # Initialize GitHub client
        client = GitHubClient()

        # Verify repository access first
        repo_info = client.verify_repository_access()
        print(f"📁 Target Repository: {repo_info['full_name']}")
        print(f"🔗 URL: {repo_info['html_url']}")
        print()

        # Prepare test issue content
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')

        issue_title = "🔧 Test Issue - DevOps Agent GitHub Integration"

        issue_body = f"""# Test Issue - DevOps Agent GitHub Integration

**Created:** {timestamp}
**Purpose:** Verification of automated issue creation capabilities
**Source:** DevOps Agent Python automation

## Integration Details

This issue was automatically created to test:

- ✅ GitHub API authentication
- ✅ Repository access permissions
- ✅ Issue creation functionality
- ✅ Label assignment
- ✅ User assignment

## Repository Context

- **Repository:** {repo_info['full_name']}
- **Description:** {repo_info.get('description', 'No description available')}
- **Created by:** {client.username}

## Automation Framework

This issue demonstrates the DevOps Agent's ability to:

1. **Authenticate** with GitHub API using Personal Access Tokens
2. **Verify permissions** for repository operations
3. **Create structured issues** with proper metadata
4. **Apply labels and assignments** automatically
5. **Link to relevant systems** (Jira integration planned)

## Next Steps

This test issue should be reviewed and closed once automation is verified.

## Related Systems

- **DevOps Agent:** Python automation framework
- **Repository:** {repo_info['html_url']}
- **Organization:** {client.organization}

---
*Generated by DevOps Agent - GitHub Issue Automation*"""

        # Create the issue
        labels = ['automation', 'test', 'devops-agent']

        # Try to assign to current user
        assignees = [client.username]

        print("📝 Creating test issue...")
        issue_data = client.create_issue(
            title=issue_title,
            body=issue_body,
            labels=labels,
            assignees=assignees
        )

        print()
        print("🎉 Test issue creation completed!")
        print(f"   Issue: {issue_data['html_url']}")

        # Handle labels display (labels are objects with 'name' field)
        labels_str = ', '.join([label['name'] if isinstance(label, dict) and 'name' in label else str(label)
                               for label in issue_data.get('labels', [])])
        print(f"   Labels: {labels_str if labels_str else 'None'}")

        print(f"   Assigned to: {issue_data.get('assignee', {}).get('login', 'Unassigned')}")

        return issue_data

    except ValueError as e:
        print(f"❌ Error: {e}")
        return None
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        return None

if __name__ == '__main__':
    print("🚀 DevOps Agent - GitHub Test Issue Creation")
    print("=" * 50)

    result = create_automation_test_issue()

    if result:
        print()
        print("✅ SUCCESS: GitHub integration is working correctly!")
        print("You can now create issues programmatically in this repository.")
    else:
        print()
        print("❌ FAILED: Check the error messages above and verify your configuration.")
        print("Common issues:")
        print("  - Invalid or expired GitHub token")
        print("  - Insufficient repository permissions")
        print("  - Incorrect organization/repository names")
        sys.exit(1)
